CREATE TABLE "CUSTOMER" 
   (	"CUSTOMER_ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100) NOT NULL ENABLE, 
	"PHONE_NUMBER" VARCHAR2(20), 
	 PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("EMAIL")
  USING INDEX  ENABLE
   ) ;



CREATE TABLE "AUTHOR" 
   (	"AUTHOR_ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"BIOGRAPHY" VARCHAR2(4000), 
	 PRIMARY KEY ("AUTHOR_ID")
  USING INDEX  ENABLE
   ) ;



CREATE TABLE "BOOK" 
   (	"BOOK_ID" NUMBER, 
	"TITLE" VARCHAR2(100) NOT NULL ENABLE, 
	"PRICE" NUMBER NOT NULL ENABLE, 
	"STOCK" NUMBER(*,0) NOT NULL ENABLE, 
	"AUTHOR_ID" NUMBER, 
	"PUBLISHER_ID" NUMBER, 
	 PRIMARY KEY ("BOOK_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "BOOK" ADD FOREIGN KEY ("AUTHOR_ID")
	  REFERENCES "AUTHOR" ("AUTHOR_ID") ENABLE;
  ALTER TABLE "BOOK" ADD FOREIGN KEY ("PUBLISHER_ID")
	  REFERENCES "PUBLISHER" ("PUBLISHER_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BOOK_INSERT_TRIG" 
BEFORE INSERT ON Book
FOR EACH ROW
DECLARE
    n_rows INTEGER;
BEGIN
    SELECT COUNT(*) INTO n_rows FROM Book;
    DBMS_OUTPUT.PUT_LINE('Number of rows before INSERT: ' || n_rows);
END;
/
ALTER TRIGGER "BOOK_INSERT_TRIG" ENABLE;



CREATE TABLE "Order" 
   (	"ORDER_ID" NUMBER, 
	"CUSTOMER_ID" NUMBER, 
	"ORDER_DATE" DATE NOT NULL ENABLE, 
	"STATUS" VARCHAR2(50) NOT NULL ENABLE, 
	 PRIMARY KEY ("ORDER_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "Order" ADD FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMER" ("CUSTOMER_ID") ENABLE;



CREATE TABLE "ORDER_ITEM" 
   (	"ORDER_ITEM_ID" NUMBER, 
	"ORDER_ID" NUMBER, 
	"BOOK_ID" NUMBER, 
	"QUANTITY" NUMBER(*,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ORDER_ITEM_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "ORDER_ITEM" ADD CONSTRAINT "FK_ORDER_ITEM_BOOK_ID" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "BOOK" ("BOOK_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ORDER_ITEM" ADD FOREIGN KEY ("ORDER_ID")
	  REFERENCES "Order" ("ORDER_ID") ENABLE;



CREATE TABLE "PAYMENT" 
   (	"PAYMENT_ID" NUMBER, 
	"ORDER_ID" NUMBER, 
	"PAYMENT_DATE" DATE NOT NULL ENABLE, 
	"AMOUNT" NUMBER NOT NULL ENABLE, 
	"PAYMENT_METHOD" VARCHAR2(50), 
	 PRIMARY KEY ("PAYMENT_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "PAYMENT" ADD FOREIGN KEY ("ORDER_ID")
	  REFERENCES "Order" ("ORDER_ID") ENABLE;

      

CREATE TABLE "PUBLISHER" 
   (	"PUBLISHER_ID" NUMBER, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(200), 
	"PHONE_NUMBER" VARCHAR2(20), 
	 PRIMARY KEY ("PUBLISHER_ID")
  USING INDEX  ENABLE
   ) ;

